[kismethost]
# URL path with port to kismet server
hosturl = http://127.0.0.1:2501
# String of letters and numbers
apitoken = "XXXXXXXXXXXXXXXXXXXXXX" 
[kitsettings]
# DEBUG, INFO, WARNING, ERROR, CRITICAL
loglevel = INFO
[updatefrequency]
devicefeed = 1.0
messagefeed = 1.0
headerupdate = 2.0