[kismethost]
# URL path with port to kismet server
hosturl = "http://xx.xx.xx.xx:2501"
# String of letters and numbers
apitoken = "XXXXXXXXXXXXXXXXXXXXXX" 
[kitsettings]
# DEBUG, INFO, WARNING, ERROR, CRITICAL
loglevel = DEBUG
[updatefrequency]
devicefeed = 1.0
messagefeed = 1.0
headerupdate = 2.0